events {}

http {

  upstream backend_servers {
      server 10.0.2.200:3000;
  }

  server {
      listen 80;

      location / {
          root /usr/share/nginx/html;
          index index.html;
      }

      location /api/ {
          proxy_pass http://backend_servers;
      }

  }

}
