events {}

http {

  upstream backend_servers {
      server 10.0.2.200:3000;
  }

        server {
                listen 443 ssl;

                server_name signupapp.duckdns.org;

                ssl_certificate /etc/letsencrypt/live/signupapp.duckdns.org/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/signupapp.duckdns.org/privkey.pem;

                location / {
                        root /usr/share/nginx/html;
                        index index.html;
                }

                location /api/ {
                        proxy_pass http://backend_servers;
                }
        }
}
